### ISSUE TITLE
VSCode extension is crashing on extension load

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#164]
Sorry guys, had another issue with the latest v0.1.5 release.
It seems to work fine initially, showing problems within the editor's Problems panel, but as soon as I click on an item, the extension crashes and it shows the Output:

```
Handler does not respond to on_initialized
Checking /Users/UserName/Shopify.nosync/ProjectFile/src/theme
Found 127 templates, and 189 offenses
undefined method `+' for nil:NilClass
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/offense.rb:73:in `end_column'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:110:in `range'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:81:in `offense_to_diagnostic'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:74:in `block in send_diagnostic'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:74:in `map'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:74:in `send_diagnostic'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:58:in `block in send_diagnostics'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:56:in `each'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:56:in `send_diagnostics'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:50:in `analyze_and_send_offenses'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/handler.rb:35:in `on_text_document_did_open'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:89:in `process_request'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:30:in `block in listen'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:29:in `loop'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server/server.rb:29:in `listen'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/lib/theme_check/language_server.rb:8:in `start'
/usr/local/Cellar/theme-check/0.2.2/gems/theme-check-0.2.2/exe/theme-check-language-server:11:in `<top (required)>'
/usr/local/bin/theme-check-language-server:6:in `load'
/usr/local/bin/theme-check-language-server:6:in `<main>'
[Error - 10:10:40 PM] Connection to server is erroring. Shutting down server.
[Error - 10:10:40 PM] Connection to server is erroring. Shutting down server.
[Error - 10:10:40 PM] Connection to server is erroring. Shutting down server.
```

On the plus side, it's no longer hammering my CPU 😅

**Comment by ConduciveMammal** [comment]
Oh actually, the above looks to be same crash output as https://github.com/Shopify/theme-check/issues/147#issuecomment-776761636

**Comment by macournoyer** [comment]
@ConduciveMammal hum... looks like it’s using an old version of theme check (0.2.2) we’re at 0.3.2 now.

Can you run: brew upgrade theme-check
Restart vscode, and see if that fixes it.

**Comment by ConduciveMammal** [comment]
Hmm same issue unfortunately, even after updating and restarting VSCode. Output error confirms I'm now on 0.3.2.
![image](https://user-images.githubusercontent.com/18140157/108344371-f6a5d280-71d4-11eb-999f-ce7434579028.png)

**Comment by macournoyer** [comment]
Damn! Can you paste me the backtrace you're getting, like you did before.

**Comment by jtgrenz** [comment]
I was also having this same issue. Upgrading to 0.3.2, adding the path to `theme-check` to the vscode extension settings, and then quitting and relaunching from iterm fixed this for me.

 @ConduciveMammal have you tried manually setting `"themeCheck.languageServerPath"`?

**Comment by ConduciveMammal** [comment]
> Damn! Can you paste me the backtrace you're getting, like you did before.

```
Checking /Users/Username/Shopify.nosync/ProjectFolder
Found 494 templates, and 3186 offenses
undefined method `+' for nil:NilClass
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/offense.rb:73:in `end_column'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:123:in `range'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:94:in `offense_to_diagnostic'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:87:in `block in send_diagnostic'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:87:in `map'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:87:in `send_diagnostic'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:68:in `block in send_diagnostics'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:66:in `each'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:66:in `send_diagnostics'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:53:in `analyze_and_send_offenses'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:36:in `on_text_document_did_open'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:91:in `process_request'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:32:in `block in listen'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:31:in `loop'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:31:in `listen'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server.rb:8:in `start'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/exe/theme-check-language-server:11:in `<top (required)>'
/usr/local/bin/theme-check-language-server:6:in `load'
/usr/local/bin/theme-check-language-server:6:in `<main>'
[Error - 10:34:47 AM] Connection to server got closed. Server will not be restarted.
```

@jtgrenz thanks for that, have you a link to where that's documented? Just so I can check what to add there.

**Comment by jtgrenz** [comment]
My bad. I stopped getting the language server crashed error when I added the path (`/usr/local/bin/theme-check`) to the settings and so I thought it was fixed. Looking at the output tab I just get:

```
[Info  - 9:54:27 a.m.] Connection to server got closed. Server will restart.
[Info  - 9:54:33 a.m.] Connection to server got closed. Server will restart.
[Info  - 9:54:39 a.m.] Connection to server got closed. Server will restart.
[Info  - 9:54:45 a.m.] Connection to server got closed. Server will restart.
[Error - 9:54:50 a.m.] Connection to server got closed. Server will not be restarted.
```

If I remove the path from the settings I get the same thing you do:

```
Checking /Users/Username/src/github.com/repo/project
Found 507 templates, and 2738 offenses
undefined method `+' for nil:NilClass
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/offense.rb:73:in `end_column'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:123:in `range'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:94:in `offense_to_diagnostic'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:87:in `block in send_diagnostic'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:87:in `map'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:87:in `send_diagnostic'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:68:in `block in send_diagnostics'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:66:in `each'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:66:in `send_diagnostics'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:53:in `analyze_and_send_offenses'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/handler.rb:36:in `on_text_document_did_open'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:91:in `process_request'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:32:in `block in listen'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:31:in `loop'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server/server.rb:31:in `listen'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/lib/theme_check/language_server.rb:8:in `start'
/usr/local/Cellar/theme-check/0.3.2/gems/theme-check-0.3.2/exe/theme-check-language-server:11:in `<top (required)>'
/usr/local/bin/theme-check-language-server:6:in `load'
/usr/local/bin/theme-check-language-server:6:in `<main>'
[Error - 9:49:15 a.m.] Connection to server is erroring. Shutting down server.
```

Also noteworthy, whenever I try to restart the server it seems to spawn a new process rather than remove the failed one:

[![alt](https://screenshot.click/2021-02-wikze-ug3kr.png)](https://screenshot.click/2021-02-wikze-ug3kr.png)

**Comment by ConduciveMammal** [comment]
@macournoyer huh! I just opened another project and it seems to be working fine there. I'm thinking the broken project is missing the `.theme-check.yml` file, which is causing it to crash.
My project structure is always `src/theme` so it's a slightly different structure from the default setup, which may also be why it's crashing.

**Comment by ConduciveMammal** [comment]
Gah scratch the above. A third project with `.theme-check.yml` is also crashing.
For reference, my `theme-check.yml` looks like:

```yml
root: src/theme

ignore:
  - node_modules/*
  - dist/*

# Disable some checks
TemplateLength:
  enabled: false
  # Or configure options
  max_length: 300
  exclude_schema: true
```

**Comment by jtgrenz** [comment]
My project is just a straight download from Shopify with the addition of a few dot files at the root level (.envrc, .gitignore, config.yml). I did manually add the default `.theme-check.yml` file but got the same results.  ¯\_(ツ)_/¯

**Comment by charlespwd** [comment]
> Also noteworthy, whenever I try to restart the server it seems to spawn a new process rather than remove the failed one:

Yeah couldn't figure out a way to get rid of that. It's still killing the process, though. It's simply that the logs are persisted.

**Comment by charlespwd** [comment]
It was indeed a bug. Looks like it was something about having a tag's markup ending with a newline character. I have added a unit test to cover that. We'll make a release shortly :)

**Comment by ConduciveMammal** [comment]
Thanks @charlespwd!
When the update is out, or any update for that matter, does the `theme-check` brew package need manually update as well as the VSCode or will they sync?

**Comment by charlespwd** [comment]
We need to make a release / publish the ruby gem + upgrade the brew formula. We should have a 0.3.3 out later today.

**Comment by charlespwd** [comment]
Sorry misread the question. No need to update the vscode extension, only theme check. Once it's released a brew update theme-check should do the trick (and maybe a restart server from within vscode)

**Comment by charlespwd** [comment]
Fix was released in v0.3.3. 

```
brew upgrade theme-check
```

**Comment by ConduciveMammal** [comment]
Sorry guys, that doesn't seem to have solved the issue 😞 . Restarted both VSCode and my whole computer to no avail.

```
Checking /Users/Username/Shopify.nosync/ProjectFolder/src/theme
Found 135 templates, and 235 offenses
undefined method `+' for nil:NilClass
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/offense.rb:75:in `end_column'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:123:in `range'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:94:in `offense_to_diagnostic'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:87:in `block in send_diagnostic'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:87:in `map'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:87:in `send_diagnostic'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:68:in `block in send_diagnostics'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:66:in `each'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:66:in `send_diagnostics'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:53:in `analyze_and_send_offenses'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/handler.rb:36:in `on_text_document_did_open'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/server.rb:91:in `process_request'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/server.rb:32:in `block in listen'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/server.rb:31:in `loop'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server/server.rb:31:in `listen'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/lib/theme_check/language_server.rb:8:in `start'
/usr/local/Cellar/theme-check/0.3.3/gems/theme-check-0.3.3/exe/theme-check-language-server:11:in `<top (required)>'
/usr/local/bin/theme-check-language-server:6:in `load'
/usr/local/bin/theme-check-language-server:6:in `<main>'
[Error - 2:52:59 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by charlespwd** [comment]
I'll try one more thing and add an error handler to drop a little more context the next time we have an error of the sort.

**Comment by charlespwd** [comment]
We just made a new release. Can you try again? 
```
brew update
brew upgrade theme-check
```

**Comment by ConduciveMammal** [comment]
Nice! That seems to have cracked it! Thanks!
