### ISSUE TITLE
Exception while running `ImgWidthAndHeight#on_document`:

### ISSUE THREAD

**Issue by andershagbard** [Shopify/theme-check#298]
Exception while running `ImgWidthAndHeight#on_document`:
```
Timeout::Error: execution expired
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/regex_helpers.rb:8:in `match'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/regex_helpers.rb:8:in `match'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/regex_helpers.rb:8:in `matches'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/checks/img_width_and_height.rb:28:in `record_offenses'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/checks/img_width_and_height.rb:22:in `on_document'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/checks.rb:25:in `block in call_check_method'
  /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/checks.rb:24:in `call_check_method'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/checks.rb:11:in `block in call'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/checks.rb:10:in `each'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/checks.rb:10:in `call'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/visitor.rb:36:in `call_checks'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/visitor.rb:12:in `visit_template'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/analyzer.rb:41:in `block in analyze_theme'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/analyzer.rb:41:in `each'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/analyzer.rb:41:in `analyze_theme'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/cli.rb:157:in `check'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/cli.rb:97:in `run!'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/cli.rb:101:in `run'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/lib/theme_check/cli.rb:119:in `parse_and_run'
  /usr/local/Cellar/theme-check/0.8.3/gems/theme-check-0.8.3/exe/theme-check:6:in `<top (required)>'
  /usr/local/bin/theme-check:6:in `load'
  /usr/local/bin/theme-check:6:in `<main>'
```

Template: `snippets/image-lazy.liquid`
Node: `Liquid::Document`
Markup: ``` ```
Theme Check Version: 0.8.3
Ruby Version: 3.0.1
Platform: x86_64-darwin20
Muffin mode: activated

**image-lazy.liquid**
```liquid
{%- liquid
  capture size
    echo '{width}x{height}'
  endcapture
  assign widths = '30,60,90,120,150,180,210,240,270,300,330,360,390,420,450,480,510,540,570,600,630,660,690,720,750,780,810,840,870,900,930,960,990,1020,1050,1080,1110,1140,1170,1200,1230,1260,1290,1320,1350,1380,1410,1440,1470,1500,1530,1560,1590,1620,1650,1680,1710,1740,1770,1800,1830,1860,1890,1920,1950,1980,2010,2040,2070,2100,2130,2160,2190,2220,2250,2280,2310,2340,2370,2400,2430,2460,2490,2520,2550,2580,2610,2640,2670,2700,2730,2760,2790,2820,2850,2880' | split: ','

  capture widths
    for width in widths
      assign widthInt = width | abs

      if aspect != blank
        assign heightInt = widthInt | divided_by: aspect

        if image.width <= widthInt
          break
        endif

        if image.height <= heightInt
          break
        endif

        unless forloop.first
          echo ','
        endunless

        echo width
      else
        if image.width <= widthInt
          break
        endif

        unless forloop.first
          echo ','
        endunless

        echo width
      endif
    endfor
  endcapture
-%}

<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
     data-src="{{ image | img_url: '1x1', crop: 'center' | replace: '1x1', size }}"
     data-aspectratio="{{ aspect }}"
     data-sizes="auto"
     data-widths="[{{ widths }}]"
     alt="{{ image.alt }}"
     class="{{ class | append: ' lazyload' | strip }}"
     decoding="async"
     {{ attributes }}>
```

**Comment by mashkovtsevlx** [comment]
I have the same issue.
Theme Check Version: 0.8.3
Ruby Version: 3.0.1
Platform: x86_64-darwin20
Muffin mode: activated
