### ISSUE TITLE
Exception while running `RemoteAsset#on_document`

### ISSUE THREAD

**Issue by hta218** [Shopify/theme-check#305]
Got `Exception while running 'RemoteAsset#on_document'` while running `theme-check` on my development theme

Script logs:

```bash
$ theme-check
Checking . ...
Exception while running 'RemoteAsset#on_document':

Timeout::Error: execution expired
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/regex_helpers.rb:8:in 'match'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/regex_helpers.rb:8:in 'match'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/regex_helpers.rb:8:in 'matches'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/checks/remote_asset.rb:67:in 'record_html_offenses'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/checks/remote_asset.rb:41:in 'on_document'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/checks.rb:33:in 'block in call_check_method'
  /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/timeout.rb:112:in 'timeout'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/checks.rb:32:in 'call_check_method'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/checks.rb:11:in 'block in call'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/checks.rb:10:in 'each'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/checks.rb:10:in 'call'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/visitor.rb:35:in 'call_checks'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/visitor.rb:23:in 'visit'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/visitor.rb:12:in 'visit_template'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/analyzer.rb:38:in 'block in analyze_theme'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/analyzer.rb:37:in 'each'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/analyzer.rb:37:in 'analyze_theme'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/cli.rb:157:in 'check'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/cli.rb:97:in 'run!'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/cli.rb:101:in 'run'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/lib/theme_check/cli.rb:119:in 'parse_and_run'
  /usr/local/Cellar/theme-check/0.9.0/gems/theme-check-0.9.0/exe/theme-check:6:in '<top (required)>'
  /usr/local/bin/theme-check:6:in 'load'
  /usr/local/bin/theme-check:6:in '<main>'

Template: 'snippets/native-responsive-image.liquid'
Node: 'Liquid::Document'
Markup:

Check options: {}

Theme Check Version: 0.9.0
Ruby Version: 3.0.1
Platform: x86_64-darwin20
Muffin mode: activated

------------------------
Whoops! It looks like you found a bug in Theme Check.
Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
Or cross your fingers real hard, and try again.
```

My liquid file `snippets/native-responsive-image.liquid` content:

```liquid
{%- comment -%}
    Accepts:
    - image: {Object} Image object
    - img_url: {String} Optional image Size URL, you need to pass the width, height via image_attributes variable
    - image_class: {String} class name of the <img />
    - image_attributes: {String}  additional HTML attributes of the <img />
    - sizes: {String}  image sizes if need

    Usage:
    In your liquid template file, copy the following line
    - {% render 'native-responsive-image', image: featured_image, image_class: "css-class", image_attributes: "some-attributes" %}
{%- endcomment -%}
{%- if img_url -%}
    <img
        src="{{ img_url }}" loading="lazy"
        class="transition-all opacity-0 {{ image_class }}"
        {%- if alt != null -%} alt="{{ alt | escape }}" {%- endif -%}
        onload="this.classList.add('opacity-100')"
        {{ image_attributes }}
    >
{%- else -%}
    <img
        srcset="{%- if image.width >= 320 -%}{{ image | img_url: '320x' }} 320w,{%- endif -%}{%- if image.width >= 640 -%}{{ image | img_url: '640x' }} 640w,{%- endif -%}{%- if image.width >= 768 -%}{{ image | img_url: '768x' }} 768w,{%- endif -%}{%- if image.width >= 1024 -%}{{ image | img_url: '1024x' }} 1024w,{%- endif -%}{%- if image.width >= 1280 -%}{{ image | img_url: '1280x' }} 1280w,{%- endif -%}{%- if image.width >= 1536 -%}{{ image | img_url: 'master' }} 1536w{%- endif -%}"
        sizes="{%- if sizes != null -%}{{ sizes }}{%- else -%}(min-width: 1536px) 1536px, (min-width: 1230px) 1230px, (min-width: 1025px) 1025px, (min-width: 768px) 768px, (min-width: 576px) 576px, 576px{%- endif -%}"
        src="{{ image | img_url: '320x' }}"
        width="{{ image.width }}" height="{{ image.height }}"
        loading="lazy"
        class="transition-all opacity-0 {{ image_class }}"
        onload="this.classList.add('opacity-100')"
        {%- if image.alt != null -%} alt="{{ image.alt | escape }}" {%- endif -%}
        {{ image_attributes }}
    >
{%- endif -%}
```

Any idea?

**Comment by macournoyer** [comment]
Aye! This would likely be fixed by #303. I might have time to do this later this week.

Thanks for reporting Tuan!
