### ISSUE TITLE
Theme Check Language Server crashed 5 times

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#317]
Been receiving this error on a couple of projects recently, not all but some.

Currently running theme-check `0.10.1`

```
Checking /Users/liammerlyn/Shopify.nosync/ProjectName/src/theme
Attributes per element limit exceeded
/usr/local/Cellar/theme-check/0.10.1/gems/nokogumbo-2.0.5/lib/nokogumbo/html5/document_fragment.rb:19:in `fragment'
/usr/local/Cellar/theme-check/0.10.1/gems/nokogumbo-2.0.5/lib/nokogumbo/html5/document_fragment.rb:19:in `initialize'
/usr/local/Cellar/theme-check/0.10.1/gems/nokogumbo-2.0.5/lib/nokogumbo/html5/document_fragment.rb:33:in `new'
/usr/local/Cellar/theme-check/0.10.1/gems/nokogumbo-2.0.5/lib/nokogumbo/html5/document_fragment.rb:33:in `parse'
/usr/local/Cellar/theme-check/0.10.1/gems/nokogumbo-2.0.5/lib/nokogumbo/html5.rb:28:in `fragment'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/html_visitor.rb:21:in `parse'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/html_visitor.rb:14:in `visit_template'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/analyzer.rb:39:in `block in analyze_theme'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/analyzer.rb:37:in `each'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/analyzer.rb:37:in `analyze_theme'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/handler.rb:136:in `block in analyze_and_send_offenses'
/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/handler.rb:135:in `analyze_and_send_offenses'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/handler.rb:59:in `on_text_document_did_open'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:96:in `process_request'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:36:in `block in listen'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:35:in `loop'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:35:in `listen'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server.rb:21:in `start'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/exe/theme-check-language-server:10:in `<top (required)>'
/usr/local/bin/theme-check-language-server:6:in `load'
/usr/local/bin/theme-check-language-server:6:in `<main>'
[Error - 10:59:09] Connection to server got closed. Server will not be restarted.
[Error - 10:59:09] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:35828)
	at Object.dispose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:116000)
	at w.handleConnectionClosed (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:116213)
	at w.handleConnectionClosed (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:176601)
	at t (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:114302)
	at r.invoke (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:37441)
	at o.fire (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:38202)
	at Y (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:25086)
	at r.invoke (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:37441)
	at o.fire (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:38202)
	at m.fireClose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:46083)
	at Socket.<anonymous> (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.2.2/dist/extension.js:1:47668)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```

**Comment by ConduciveMammal** [comment]
>Do you happen to know if you've got any HTML element w/ lots of attributes in one of your templates?

Almost certainly, the theme's a right mess. I wouldn't be able to point it out though.
