### ISSUE TITLE
`undefined method liquid?`whilst working in ignored files.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#339]
I'm working in the theme's `theme.js` file, which I've set to ignore in `theme-check.yml` and it seems to be crashing repeatedly, potentially due to the ignores.

My config contains:`
```yml
ignore:
  - assets/*.css.liquid
  - assets/*.min.css.liquid
  - assets/*.js.liquid
  - assets/*.min.js.liquid
  - assets/*.scss.liquid
  - assets/*.min.scss.liquid
```

The crash log says:
```Checking assets/theme.js
undefined method `liquid?' for #<ThemeCheck::AssetFile:0x00007fa7ff3dc9e0 @relative_path="assets/theme.js", @storage=#<ThemeCheck::FileSystemStorage:0x00007fa7ffa41830 @root=#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme>, @ignored_patterns=["assets/*.css.liquid", "assets/*.min.css.liquid", "assets/*.js.liquid", "assets/*.min.js.liquid", "assets/*.scss.liquid", "assets/*.min.scss.liquid"], @files={"layout/gift-card.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/layout/gift-card.liquid>, "layout/password.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/layout/password.liquid>, "layout/theme.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/layout/theme.liquid>, "sections/announcement-bar.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/announcement-bar.liquid>, "sections/article.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/article.liquid>, "sections/blog-posts.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/blog-posts.liquid>, "sections/blog.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/blog.liquid>, "sections/code.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/code.liquid>, "sections/collection-list.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/collection-list.liquid>, "sections/collection-portfolio.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/collection-portfolio.liquid>, "sections/collection.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/collection.liquid>, "sections/faq.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/faq.liquid>, "sections/featured-collection.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/featured-collection.liquid>, "sections/featured-product.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/featured-product.liquid>, "sections/footer.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/footer.liquid>, "sections/gallery.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/gallery.liquid>, "sections/gift-card.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/gift-card.liquid>, "sections/heading.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/heading.liquid>, "sections/image-with-text.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/image-with-text.liquid>, "sections/list-collections.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/list-collections.liquid>, "sections/maestrooo-instagram.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/maestrooo-instagram.liquid>, "sections/newsletter.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/newsletter.liquid>, "sections/password.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/password.liquid>, "sections/pebbles.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/pebbles.liquid>, "sections/popup.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/popup.liquid>, "sections/product-portfolio.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/product-portfolio.liquid>, "sections/product-recommendations.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/product-recommendations.liquid>, "sections/product-story.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/product-story.liquid>, "sections/product.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/product.liquid>, "sections/review-section.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/review-section.liquid>, "sections/rich-text.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/rich-text.liquid>, "sections/search.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/search.liquid>, "sections/shop-the-look.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/shop-the-look.liquid>, "sections/sidebar.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/sidebar.liquid>, "sections/slider-horizontal.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/slider-horizontal.liquid>, "sections/slider-vertical.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/slider-vertical.liquid>, "sections/store-availability.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/store-availability.liquid>, "sections/testimonials-columns.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/testimonials-columns.liquid>, "sections/testimonials.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/testimonials.liquid>, "sections/text-columns-with-icons.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/text-columns-with-icons.liquid>, "sections/text-columns-with-images.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/text-columns-with-images.liquid>, "sections/video-background.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/video-background.liquid>, "sections/video-popup.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/sections/video-popup.liquid>, "snippets/blog-item.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/blog-item.liquid>, "snippets/breadcrumb.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/breadcrumb.liquid>, "snippets/cart-form.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/cart-form.liquid>, "snippets/collection-item.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/collection-item.liquid>, "snippets/form-errors.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/form-errors.liquid>, "snippets/head-variables.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/head-variables.liquid>, "snippets/icons-pack.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/icons-pack.liquid>, "snippets/image-with-text-content.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/image-with-text-content.liquid>, "snippets/lazy-image.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/lazy-image.liquid>, "snippets/localization-form.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/localization-form.liquid>, "snippets/microdata-schema.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/microdata-schema.liquid>, "snippets/open-graph.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/open-graph.liquid>, "snippets/pagination.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/pagination.liquid>, "snippets/product-item-portfolio.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/product-item-portfolio.liquid>, "snippets/product-item.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/product-item.liquid>, "snippets/product-media.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/product-media.liquid>, "snippets/product-quantity.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/product-quantity.liquid>, "snippets/rich-text-content.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/rich-text-content.liquid>, "snippets/search-form.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/search-form.liquid>, "snippets/share-popup.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/share-popup.liquid>, "snippets/shop-svg-logo.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/shop-svg-logo.liquid>, "snippets/sidebar-navigation.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/sidebar-navigation.liquid>, "snippets/social-icons.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/social-icons.liquid>, "snippets/svg-pebbles.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/svg-pebbles.liquid>, "snippets/svg-sprite.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/svg-sprite.liquid>, "snippets/text-columns-with-images-content.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/text-columns-with-images-content.liquid>, "snippets/theme-symbols.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/theme-symbols.liquid>, "snippets/video-background-content.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/snippets/video-background-content.liquid>, "templates/404.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/404.liquid>, "templates/article.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/article.liquid>, "templates/blog.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/blog.liquid>, "templates/cart.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/cart.liquid>, "templates/collection.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/collection.liquid>, "templates/collection.portfolio.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/collection.portfolio.liquid>, "templates/customers/account.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/customers/account.liquid>, "templates/customers/activate_account.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/customers/activate_account.liquid>, "templates/customers/addresses.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/customers/addresses.liquid>, "templates/customers/login.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/customers/login.liquid>, "templates/customers/order.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/customers/order.liquid>, "templates/customers/register.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/customers/register.liquid>, "templates/customers/reset_password.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/customers/reset_password.liquid>, "templates/gift_card.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/gift_card.liquid>, "templates/index.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/index.liquid>, "templates/list-collections.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/list-collections.liquid>, "templates/page.contact.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/page.contact.liquid>, "templates/page.faq.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/page.faq.liquid>, "templates/page.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/page.liquid>, "templates/password.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/password.liquid>, "templates/product.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/product.liquid>, "templates/product.portfolio.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/product.portfolio.liquid>, "templates/search.liquid"=>#<Pathname:/Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme/templates/search.liquid>}, @file_array=["assets", "assets/arrow-left.svg", "assets/arrow-right.svg", "assets/jquery.matchHeight.js", "assets/sidebar.jpg", "assets/sidebar.png", "assets/theme.css", "assets/theme.js", "assets/theme.min.js", "config", "config/settings_schema.json", "layout", "layout/gift-card.liquid", "layout/password.liquid", "layout/theme.liquid", "sections", "sections/announcement-bar.liquid", "sections/article.liquid", "sections/blog-posts.liquid", "sections/blog.liquid", "sections/code.liquid", "sections/collection-list.liquid", "sections/collection-portfolio.liquid", "sections/collection.liquid", "sections/faq.liquid", "sections/featured-collection.liquid", "sections/featured-product.liquid", "sections/footer.liquid", "sections/gallery.liquid", "sections/gift-card.liquid", "sections/heading.liquid", "sections/image-with-text.liquid", "sections/list-collections.liquid", "sections/maestrooo-instagram.liquid", "sections/newsletter.liquid", "sections/password.liquid", "sections/pebbles.liquid", "sections/popup.liquid", "sections/product-portfolio.liquid", "sections/product-recommendations.liquid", "sections/product-story.liquid", "sections/product.liquid", "sections/review-section.liquid", "sections/rich-text.liquid", "sections/search.liquid", "sections/shop-the-look.liquid", "sections/sidebar.liquid", "sections/slider-horizontal.liquid", "sections/slider-vertical.liquid", "sections/store-availability.liquid", "sections/testimonials-columns.liquid", "sections/testimonials.liquid", "sections/text-columns-with-icons.liquid", "sections/text-columns-with-images.liquid", "sections/video-background.liquid", "sections/video-popup.liquid", "snippets", "snippets/blog-item.liquid", "snippets/breadcrumb.liquid", "snippets/cart-form.liquid", "snippets/collection-item.liquid", "snippets/form-errors.liquid", "snippets/head-variables.liquid", "snippets/icons-pack.liquid", "snippets/image-with-text-content.liquid", "snippets/lazy-image.liquid", "snippets/localization-form.liquid", "snippets/microdata-schema.liquid", "snippets/open-graph.liquid", "snippets/pagination.liquid", "snippets/product-item-portfolio.liquid", "snippets/product-item.liquid", "snippets/product-media.liquid", "snippets/product-quantity.liquid", "snippets/rich-text-content.liquid", "snippets/search-form.liquid", "snippets/share-popup.liquid", "snippets/shop-svg-logo.liquid", "snippets/sidebar-navigation.liquid", "snippets/social-icons.liquid", "snippets/svg-pebbles.liquid", "snippets/svg-sprite.liquid", "snippets/text-columns-with-images-content.liquid", "snippets/theme-symbols.liquid", "snippets/video-background-content.liquid", "templates", "templates/404.liquid", "templates/article.liquid", "templates/blog.liquid", "templates/cart.liquid", "templates/collection.liquid", "templates/collection.portfolio.liquid", "templates/customers", "templates/customers/account.liquid", "templates/customers/activate_account.liquid", "templates/customers/addresses.liquid", "templates/customers/login.liquid", "templates/customers/order.liquid", "templates/customers/register.liquid", "templates/customers/reset_password.liquid", "templates/gift_card.liquid", "templates/index.liquid", "templates/list-collections.liquid", "templates/page.contact.liquid", "templates/page.faq.liquid", "templates/page.liquid", "templates/password.liquid", "templates/product.liquid", "templates/product.portfolio.liquid", "templates/search.liquid"]>, @loaded=false, @content=nil, @relative_pathname=#<Pathname:assets/theme.js>>
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/analyzer.rb:63:in `block in analyze_files'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/analyzer.rb:62:in `each'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/analyzer.rb:62:in `analyze_files'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/handler.rb:149:in `block in analyze_and_send_offenses'
/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/handler.rb:148:in `analyze_and_send_offenses'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/handler.rb:63:in `on_text_document_did_save'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:96:in `process_request'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:36:in `block in listen'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:35:in `loop'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server/server.rb:35:in `listen'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/lib/theme_check/language_server.rb:21:in `start'
/usr/local/Cellar/theme-check/0.10.1/gems/theme-check-0.10.1/exe/theme-check-language-server:10:in `<top (required)>'
/usr/local/bin/theme-check-language-server:6:in `load'
/usr/local/bin/theme-check-language-server:6:in `<main>'
[Info  - 12:11:38] Connection to server got closed. Server will restart.
[Error - 12:11:38] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:35828)
	at Object.dispose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:116000)
	at w.handleConnectionClosed (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:116213)
	at w.handleConnectionClosed (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:176601)
	at t (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:114302)
	at r.invoke (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:37441)
	at o.fire (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:38202)
	at Y (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:25086)
	at r.invoke (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:37441)
	at o.fire (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:38202)
	at m.fireClose (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:46083)
	at Socket.<anonymous> (/Users/liammerlyn/.vscode/extensions/shopify.theme-check-vscode-0.3.3/dist/extension.js:1:47668)
	at Socket.emit (events.js:327:22)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)
Checking /Users/liammerlyn/Shopify.nosync/ProjectFolder/src/theme
Found 118 offenses in 3.14s
```

**Comment by ConduciveMammal** [comment]
@macournoyer I still seem to be having this issue after updating to `1.0.0`. Fully restarted VSCode with no difference. New checks are showing up so upgrade is fully enabled.

**Comment by macournoyer** [comment]
@ConduciveMammal aarg! That's the thing w/ auto-closing issues in GitHub 😄  It's fixed on `master`, but not yet released. I will do a release this AM, sorry about that.

**Comment by ConduciveMammal** [comment]
Ahhh! Is `master` not the public release branch then? Hah, no worries at all.

**Comment by macournoyer** [comment]
> Is `master` not the public release branch then?

It is, but we still have to bump the version & release manually.

**Comment by ConduciveMammal** [comment]
Smashing! Thanks a lot! 👏🏻

**Comment by charlespwd** [comment]
The VS Code extension is now backed by the Shopify CLI (if installed), and then theme-check (if installed) in that order. We're seeing that it's using the shopify-cli gem from the stack trace here:

```
/usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/bin/shopify:
                              ^^^^^                  ^^^^^
```
