### ISSUE TITLE
Bug in Theme Check on load VS Code, resulting in server not being restarted

### ISSUE THREAD

**Issue by KyButler** [Shopify/theme-check#417]
Checking /Users/{userfolder}/Documents/{subfolder}/{subfolder}/{root_directory}
Exception while running `PaginationSize#after_document`:
```
ArgumentError: comparison of String with 50 failed
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:48:in `>'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:48:in `block in after_document'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:40:in `each_pair'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:40:in `after_document'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
  /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
  /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:41:in `call_check_method'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:11:in `block in call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `each'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:35:in `call_checks'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:26:in `visit'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:12:in `visit_template'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:39:in `block (2 levels) in analyze_theme'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in `each'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in `block in analyze_theme'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check.rb:57:in `with_liquid_c_disabled'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:37:in `analyze_theme'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:139:in `block in analyze_and_send_offenses'
  /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:138:in `analyze_and_send_offenses'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:60:in `on_text_document_did_open'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/project_types/theme/commands/language_server.rb:8:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:20:in `log'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <top (required)>'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
  /opt/homebrew/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<top (required)>'
  /opt/homebrew/bin/shopify:6:in `load'
  /opt/homebrew/bin/shopify:6:in `<main>'
```

Template: `sections/blog-template.liquid`
Node: `Liquid::Document`
Markup:
```

```
Check options: `{:min_size=>1, :max_size=>50}
`
Theme Check Version: 1.4.0
Ruby Version: 3.0.2
Platform: arm64-darwin20
Muffin mode: activated

------------------------
Whoops! It looks like you found a bug in Theme Check.
Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
Or cross your fingers real hard, and try again.

**Comment by KyButler** [comment]
```shopify theme check```

also causes this same issue. This is the sections/blog-template.liquid.

```
{%- paginate blog.articles by section.settings.articles_per_page -%}

<!-- ARTICLES -->
<div class="articles">

    {%- if section.settings.article_style == 'list' -%}

        {%- for article in blog.articles -%}

            <!-- ARTICLE ITEM -->
            {%- include 'article-list-item' -%}
            <!-- / ARTICLE ITEM -->

        {%- endfor -%}

    {%- else -%}

        {%- include 'util-column-class' column_count: section.settings.articles_per_row, column_min: section.settings.articles_per_row_mobile -%}
        {%- assign article_image_ratio = settings.article_image_aspect_ratio_w | plus :0.0 | divided_by: settings.article_image_aspect_ratio_h -%}
        {%- include 'util-image-size' column_count: section.settings.articles_per_row, image_ratio: article_image_ratio, custom_ratio: settings.enable_article_custom_aspect_ratio -%}

        {% capture item_class %}{{ column_class }} animate-on-scroll{% endcapture %}

        <div class="row">

            {%- for article in blog.articles -%}

                <!-- ARTICLE ITEM -->
                {%- include 'article-grid-item'
                style: section.settings.article_style,
                image_size: image_size
                item_class: item_class -%}
                <!-- / ARTICLE ITEM -->

            {%- endfor -%}

        </div>

    {%- endif -%}

    {%- if blog.articles.size == 0 -%}
        <p><em>{{ 'blogs.no_posts' | t }}</em></p>
    {%- endif -%}

    {%- if paginate.pages > 1 -%}
        <!-- PAGINATON -->
        {%- include 'pagination' -%}
        <!-- / PAGINATON -->
    {%- endif -%}

    <div>
        <a class="text-light" href="{{ blog.url }}.atom">
            <span class="icon icon-rss s-6"></span>
        </a>
    </div>

</div>
<!-- / ARTICLES -->

{%- endpaginate -%}

<script type="application/json">
    /*"*/{% schema %}/*"*/
    {
        "name": "Blog",
        "settings": [
            {
                "type": "header",
                "content": "Articles"
            },
            {
                "type": "checkbox",
                "id": "show_author",
                "label": "Show author on article list style",
                "default": true
            },
            {
                "type": "select",
                "id": "article_style",
                "label": "Article listing style",
                "default": "list",
                "options": [
                    {
                        "value": "classic",
                        "label": "Classic Grid"
                    },
                    {
                        "value": "small-card",
                        "label": "Small Card Grid"
                    },
                    {
                        "value": "tall-card",
                        "label": "Tall Card Grid"
                    },
                    {
                        "value": "list",
                        "label": "List"
                    }
                ]
            },
            {
                "type": "select",
                "id": "articles_per_row",
                "label": "Number of articles per row",
                "info": "Except the 'List' style",
                "default": "4",
                "options": [
                    {
                        "value": "2",
                        "label": "2"
                    },
                    {
                        "value": "3",
                        "label": "3"
                    },
                    {
                        "value": "4",
                        "label": "4"
                    },
                    {
                        "value": "5",
                        "label": "5"
                    },
                    {
                        "value": "6",
                        "label": "6"
                    }
                ]
            },
            {
                "type": "select",
                "id": "articles_per_page",
                "label": "Number of articles per page",
                "default": "20",
                "options": [
                    {
                        "value": "1",
                        "label": "1"
                    },
                    {
                        "value": "5",
                        "label": "5"
                    },
                    {
                        "value": "10",
                        "label": "10"
                    },
                    {
                        "value": "15",
                        "label": "15"
                    },
                    {
                        "value": "20",
                        "label": "20"
                    },
                    {
                        "value": "25",
                        "label": "25"
                    },
                    {
                        "value": "30",
                        "label": "30"
                    }
                ]
            },
            {
                "type": "header",
                "content": "Mobile Specific Options"
            },
            {
                "type": "select",
                "id": "articles_per_row_mobile",
                "label": "Number of articles per row (Mobile)",
                "info": "Except the 'List' style",
                "default": "1",
                "options": [
                    {
                        "value": "1",
                        "label": "1"
                    },
                    {
                        "value": "2",
                        "label": "2"
                    }
                ]
            }
        ]
    }
    /*"*/{% endschema %}/*"*/
</script>
```

**Comment by charlespwd** [comment]
Definitely a bug. Right now it looks like our code is not smart enough to ignore assignments.

Until we fix this, you can turn off that check.

```
PaginationSize:
  enabled: false
```
