### ISSUE TITLE
Got an error when run theme-check

### ISSUE THREAD

**Issue by pebiantara** [Shopify/theme-check#428]
Hi there,
i unable to run theme-check with version 1.5.0, please check about error detail 
Checking build ...
Exception while running `PaginationSize#after_document`:
```
NoMethodError: undefined method `empty?' for nil:NilClass
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:58:in `get_setting_default_value'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:44:in `block in after_document'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:40:in `each_pair'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks/pagination_size.rb:40:in `after_document'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /Users/pebiantara/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
  /Users/pebiantara/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
  /Users/pebiantara/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
  /Users/pebiantara/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
  /Users/pebiantara/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks.rb:41:in `call_check_method'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks.rb:11:in `block in call'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks.rb:10:in `each'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/checks.rb:10:in `call'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/visitor.rb:35:in `call_checks'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/visitor.rb:26:in `visit'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/visitor.rb:12:in `visit_template'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:39:in `block (2 levels) in analyze_theme'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:38:in `each'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:38:in `block in analyze_theme'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check.rb:57:in `with_liquid_c_disabled'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/analyzer.rb:37:in `analyze_theme'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/cli.rb:183:in `check'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/cli.rb:114:in `run!'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/cli.rb:118:in `run'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/lib/theme_check/cli.rb:140:in `parse_and_run'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/gems/theme-check-1.5.0/exe/theme-check:6:in `<top (required)>'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/bin/theme-check:23:in `load'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/bin/theme-check:23:in `<main>'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
  /Users/pebiantara/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
```

Template: `templates/blog.liquid`
Node: `Liquid::Document`
Markup:
```

```
Check options: `{:min_size=>1, :max_size=>50}
`
Theme Check Version: 1.5.0
Ruby Version: 2.7.4
Platform: x86_64-darwin19
Muffin mode: activated

------------------------

**Comment by charlespwd** [comment]
In the meantime, you can disable this check by adding the following to your `.theme-check.yml` file

```
PaginationSize:
  enabled: false
```
