### ISSUE TITLE
Error when running auto-correct

### ISSUE THREAD

**Issue by hugoburguete** [Shopify/theme-check#439]
As the title states, I'm getting an error when running the auto-correct flag. The command run was `shopify theme check -a` 
 and the error details are:

```
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/node.rb:124:in `range': undefined method `+' for nil:NilClass (NoMethodError)
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/corrector.rb:21:in `replace'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/convert_include_to_render.rb:11:in `block in on_include'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/offense.rb:145:in `correct'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:88:in `each'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:88:in `correct_offenses'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:184:in `check'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:114:in `run!'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:118:in `run'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/project_types/theme/commands/check.rb:25:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<top (required)>'
        from /usr/local/bin/shopify:6:in `load'
        from /usr/local/bin/shopify:6:in `<main>'
```

Any ideas? Happy to give more details if required.

Thanks

**Comment by charlespwd** [comment]
I think I do. I noticed a flaw in our `Node.range` function when fixing #423. Seems like it didn't take long for the flaw to appear in the wild.

Thanks for flagging! I'm jumping on this.
