### ISSUE TITLE
Extension crashing

### ISSUE THREAD

**Issue by Benecke** [Shopify/theme-check#451]
Lately, the extension is crashing on my projects until it is not restarted anymore.

This is my error log. If I can provide you with any additional info, let me know.

```
Lately, the extension is crashing on my projects until it is not restarted anymore.

This is my error log. If I can provide you with any additional info, let me know.

/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/bug.rb:20:in 'bug'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:54:in 'rescue in call_check_method'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:29:in 'call_check_method'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:11:in 'block in call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in 'each'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:35:in 'call_checks'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:26:in 'visit'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:12:in 'visit_template'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:39:in 'block (2 levels) in analyze_theme'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in 'each'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in 'block in analyze_theme'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check.rb:57:in 'with_liquid_c_disabled'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:37:in 'analyze_theme'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:139:in 'block in analyze_and_send_offenses'
/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/benchmark.rb:293:in 'measure'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:138:in 'analyze_and_send_offenses'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:60:in 'on_text_document_did_open'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in 'process_request'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in 'block in listen'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in 'loop'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in 'listen'
/usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in 'start'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/project_types/theme/commands/language_server.rb:8:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in 'block (2 levels) in call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in 'block (2 levels) in with_logging'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in 'with_id'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in 'block in with_logging'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in 'log_output_to'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in 'with_logging'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in 'block in call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in 'block (2 levels) in with_traps'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in 'twrap'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in 'block in with_traps'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in 'twrap'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in 'with_traps'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in 'block in call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:32:in 'log'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:33:in 'block in <top (required)>'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in 'handle_abort'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in 'call'
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:32:in '<top (required)>'
/usr/local/bin/shopify:6:in 'load'
/usr/local/bin/shopify:6:in '<main>'
[Info  - 11:20:16 AM] Connection to server got closed. Server will restart.
Checking /Users/TB/Sites/projectxyz/theme
Exception while running 'PaginationSize#after_document':

ArgumentError: comparison of String with 50 failed
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:48:in '>'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:48:in 'block in after_document'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:40:in 'each_pair'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/pagination_size.rb:40:in 'after_document'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:42:in 'block in call_check_method'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:97:in 'block in timeout'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in 'block in catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in 'catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in 'catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:112:in 'timeout'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:41:in 'call_check_method'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:11:in 'block in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in 'each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:35:in 'call_checks'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:26:in 'visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:12:in 'visit_template'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:39:in 'block (2 levels) in analyze_theme'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in 'each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in 'block in analyze_theme'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check.rb:57:in 'with_liquid_c_disabled'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:37:in 'analyze_theme'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:139:in 'block in analyze_and_send_offenses'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/benchmark.rb:293:in 'measure'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:138:in 'analyze_and_send_offenses'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:60:in 'on_text_document_did_open'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in 'process_request'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in 'block in listen'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in 'loop'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in 'listen'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in 'start'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/project_types/theme/commands/language_server.rb:8:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in 'block (2 levels) in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in 'block (2 levels) in with_logging'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in 'with_id'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in 'block in with_logging'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in 'log_output_to'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in 'with_logging'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in 'block in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in 'block (2 levels) in with_traps'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in 'twrap'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in 'block in with_traps'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in 'twrap'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in 'with_traps'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in 'block in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:32:in 'log'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:33:in 'block in <top (required)>'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in 'handle_abort'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in 'call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:32:in '<top (required)>'
  /usr/local/bin/shopify:6:in 'load'
  /usr/local/bin/shopify:6:in '<main>'

Template: 'sections/search-results.liquid'
Node: 'Liquid::Document'
Markup:

Check options: '{:min_size=>1, :max_size=>50}'
Theme Check Version: 1.4.0
Ruby Version: 3.0.2
Platform: x86_64-darwin20
Muffin mode: activated

------------------------
```

**Comment by charlespwd** [comment]
Hi @Benecke, this bug has been fixed in the latest version of Theme Check (we're at 1.6.0 now). Since it looks like you have been using through the shopify-cli, the easiest way to do this would be to reinstall shopify-cli.

```
brew uninstall shopify-cli
brew install shopify-cli
```

**Comment by Benecke** [comment]
Thanks a lot @charlespwd - reinstalling it that way fixed the problem.

I ran `brew upgrade` before I posted as I thought updating shopify-cli that way would keep theme-check up-to-date as well. Looks I was wrong, but I'd like to know why.

**Comment by Benecke** [comment]
Ah, I see - that makes total sense. Thank you for the detailed explanation. 👍
