### ISSUE TITLE
Theme check crashing (5 times, then quits)

### ISSUE THREAD

**Issue by surfwoodroad** [Shopify/theme-check#457]
While working on a legacy Shopify site in VS Code (on an iMac that's about 5 years old, but OS is current), this thing runs automatically and starts throwing errors:

Checking /Users/mike/Documents/[etc]
Exception while running `SpaceInsideBraces#on_tag`:
```
ArgumentError: Bad start_index
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/position.rb:112:in `initialize'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/position.rb:19:in `new'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/position.rb:19:in `initialize'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/offense.rb:63:in `new'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/offense.rb:63:in `initialize'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/check.rb:95:in `new'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/check.rb:95:in `add_offense'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks/space_inside_braces.rb:61:in `on_tag'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:41:in `call_check_method'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:11:in `block in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:35:in `call_checks'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:22:in `visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:12:in `visit_template'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:39:in `block (2 levels) in analyze_theme'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in `each'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in `block in analyze_theme'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check.rb:57:in `with_liquid_c_disabled'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:37:in `analyze_theme'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:139:in `block in analyze_and_send_offenses'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:138:in `analyze_and_send_offenses'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:60:in `on_text_document_did_open'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/project_types/theme/commands/language_server.rb:8:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:32:in `log'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <top (required)>'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
  /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<top (required)>'
  /usr/local/bin/shopify:6:in `load'
  /usr/local/bin/shopify:6:in `<main>'
```

Template: `sections/featured-product.liquid`
Node: `Liquid::If`
Markup:
```
if section.settings.enable_payment_button and product.has_only_default_variant
```
Check options: `{}
`
Theme Check Version: 1.4.0
Ruby Version: 3.0.2
Platform: x86_64-darwin20
Muffin mode: activated

------------------------
Whoops! It looks like you found a bug in Theme Check.
Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.

**Comment by charlespwd** [comment]
Hiya :wave:, this bug is fixed in the latest version of Theme-Check. 

To upgrade:

* If you have installed it via the Shopify CLI on brew, easiest way is to reinstall it to get the latest version of theme-check.

  ```
  brew uninstall shopify-cli
  brew install shopify-cli
  ```

* If you have installed it via Shopify CLI via the gem, reinstall it.

  ```
  gem uninstall shopify-cli
  gem install shopify-cli
  ```

* If you have installed theme-check via brew, upgrade it

  ```
  brew update && brew upgrade theme-check
  ```

* If you have installed it via the gem, upgrade it.

  ```
  gem update theme-check
  ```
