### ISSUE TITLE
Shopify Theme Check Crashes on Load

### ISSUE THREAD

**Issue by LloydDavid** [Shopify/theme-check#467]
Operating system - MacOS Big Sur 11.6
Tooling - Theme check via terminal and shopify liquid extension via visual studio code.
==2 Errors==:
==Error 1/2 > 
<img width="482" alt="shopify-visual-studio-code-error-1of2-Screenshot 2021-09-24 at 15 22 44" src="https://user-images.githubusercontent.com/7349510/134696513-b63933b2-b561-4fe2-b28d-6a36c66325b8.png">
Output(after button is pressed as shown in image)
Operation not permitted - /Users/lloyddavid/.Trash
<internal:dir>:134:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:30:in `files'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:91:in `in_memory_storage'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:33:in `on_initialize'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/language_server.rb:8:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <top (required)>'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<top (required)>'
/usr/local/bin/shopify:6:in `load'
/usr/local/bin/shopify:6:in `<main>'
[Info  - 3:53:40 PM] Connection to server got closed. Server will restart.
Operation not permitted - /Users/lloyddavid/.Trash
<internal:dir>:134:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:30:in `files'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:91:in `in_memory_storage'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:33:in `on_initialize'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/language_server.rb:8:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <top (required)>'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<top (required)>'
/usr/local/bin/shopify:6:in `load'
/usr/local/bin/shopify:6:in `<main>'
[Info  - 3:53:41 PM] Connection to server got closed. Server will restart.
Operation not permitted - /Users/lloyddavid/.Trash
<internal:dir>:134:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:30:in `files'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:91:in `in_memory_storage'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:33:in `on_initialize'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/language_server.rb:8:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <top (required)>'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<top (required)>'
/usr/local/bin/shopify:6:in `load'
/usr/local/bin/shopify:6:in `<main>'
[Info  - 3:53:41 PM] Connection to server got closed. Server will restart.
Operation not permitted - /Users/lloyddavid/.Trash
<internal:dir>:134:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:30:in `files'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:91:in `in_memory_storage'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:33:in `on_initialize'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/language_server.rb:8:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <top (required)>'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<top (required)>'
/usr/local/bin/shopify:6:in `load'
/usr/local/bin/shopify:6:in `<main>'
[Info  - 3:53:42 PM] Connection to server got closed. Server will restart.
Operation not permitted - /Users/lloyddavid/.Trash
<internal:dir>:134:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:52:in `glob'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/file_system_storage.rb:30:in `files'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:91:in `in_memory_storage'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/handler.rb:33:in `on_initialize'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:107:in `process_request'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:36:in `block in listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `loop'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server/server.rb:35:in `listen'
/usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/language_server.rb:26:in `start'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/language_server.rb:8:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <top (required)>'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
/usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<top (required)>'
/usr/local/bin/shopify:6:in `load'
/usr/local/bin/shopify:6:in `<main>'
[Error - 3:53:42 PM] Connection to server got closed. Server will not be restarted.

==Error 2/2 >
<img width="460" alt="shopify-visual-studio-code-error-2of2-Screenshot 2021-09-24 at 15 53 11" src="https://user-images.githubusercontent.com/7349510/134696675-78d824ea-d41d-493a-9ea4-4fd00f0b95c1.png">

**Comment by LloydDavid** [comment]
I found the issues: files that were missing > .theme-check.yml & translation.yml, please delete this issue if it's been shared already.
