### ISSUE TITLE
Exception while running `ValidHTMLTranslation#on_file`:

### ISSUE THREAD

**Issue by agriboz** [Shopify/theme-check#477]
Here is the error that when I type `shopify theme check`. Shopify CLI version is 2.5
```
NoMethodError: undefined method `end_with?' for nil:NilClass
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks/valid_html_translation.rb:22:in `html_key?'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks/valid_html_translation.rb:40:in `visit_nested'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks/valid_html_translation.rb:38:in `block in visit_nested'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks/valid_html_translation.rb:37:in `each'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks/valid_html_translation.rb:37:in `visit_nested'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks/valid_html_translation.rb:15:in `on_file'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:41:in `call_check_method'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:11:in `block in call'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `each'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `call'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:44:in `block in analyze_theme'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:44:in `each'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:44:in `analyze_theme'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:183:in `check'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:114:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:118:in `run'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/check.rb:25:in `call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <main>'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
  /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<main>'
```

Template: `?`
Node: `?`
Markup:
```

```
Check options: `{}
`
Theme Check Version: 1.4.0
Ruby Version: 2.6.3
Platform: universal.x86_64-darwin20
Muffin mode: activated
```

**Comment by Morgy93** [comment]
Same here using latest shopify-cli 2.6.6:

Open `locales/de.json`:

Add a new entry at the end:
```
  },
  "foo": "bar"
}
```

Run `theme-check`:

Checking . ...
Exception while running `ValidHTMLTranslation#on_file`:
```
NoMethodError: undefined method `end_with?' for nil:NilClass
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks/valid_html_translation.rb:22:in `html_key?'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks/valid_html_translation.rb:40:in `visit_nested'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks/valid_html_translation.rb:38:in `block in visit_nested'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks/valid_html_translation.rb:37:in `each'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks/valid_html_translation.rb:37:in `visit_nested'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks/valid_html_translation.rb:15:in `on_file'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
  /usr/local/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
  /usr/local/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/local/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/local/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks.rb:41:in `call_check_method'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks.rb:11:in `block in call'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks.rb:10:in `each'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/checks.rb:10:in `call'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/analyzer.rb:60:in `block in analyze_theme'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/analyzer.rb:58:in `each'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/analyzer.rb:58:in `each_with_index'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/analyzer.rb:58:in `analyze_theme'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/cli.rb:192:in `check'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/cli.rb:123:in `run!'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/cli.rb:127:in `run'
  /usr/local/bundle/gems/theme-check-1.7.2/lib/theme_check/cli.rb:149:in `parse_and_run'
  /usr/local/bundle/gems/theme-check-1.7.2/exe/theme-check:6:in `<top (required)>'
  /usr/local/bundle/bin/theme-check:23:in `load'
  /usr/local/bundle/bin/theme-check:23:in `<main>'
```

Theme File: `?`
Node: `?`
Markup:
```

```
Line number: ?
Check options: `{}
`
Theme Check Version: 1.7.2
Ruby Version: 3.0.2
Platform: x86_64-linux
Muffin mode: activated
