### ISSUE TITLE
Theme Check Crash: Exception while running `SpaceInsideBraces#on_tag`

### ISSUE THREAD

**Issue by robertmassaioli** [Shopify/theme-check#479]
I'm getting this error and I'm reporting it as requested:

$ shopify theme check   
Checking . ...
Exception while running `SpaceInsideBraces#on_tag`:

```
ArgumentError: Bad start_index
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/position.rb:112:in `initialize'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/position.rb:19:in `new'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/position.rb:19:in `initialize'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/offense.rb:63:in `new'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/offense.rb:63:in `initialize'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/check.rb:95:in `new'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/check.rb:95:in `add_offense'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/checks/space_inside_braces.rb:61:in `on_tag'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:41:in `call_check_method'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:11:in `block in call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/checks.rb:10:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:35:in `call_checks'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:22:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `block in visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:24:in `visit'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/visitor.rb:12:in `visit_template'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:39:in `block (2 levels) in analyze_theme'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in `each'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:38:in `block in analyze_theme'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check.rb:57:in `with_liquid_c_disabled'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/analyzer.rb:37:in `analyze_theme'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:183:in `check'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:114:in `run!'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/theme-check-1.4.0/lib/theme_check/cli.rb:118:in `run'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/check.rb:25:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:32:in `log'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <top (required)>'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
  /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<top (required)>'
  /usr/local/bin/shopify:6:in `load'
  /usr/local/bin/shopify:6:in `<main>'
```

Template: `snippets/bold-variant.liquid`
Node: `Liquid::Assign`
Markup:
```
assign third_party_hidden = true
```
Check options: `{}
`
Theme Check Version: 1.4.0
Ruby Version: 3.0.2
Platform: x86_64-darwin19
Muffin mode: activated

------------------------
Whoops! It looks like you found a bug in Theme Check.
Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
Or cross your fingers real hard, and try again.

**Comment by charlespwd** [comment]
This was fixed in 1.5 IIRC. Please upgrade shopify-cli and this bug will go away.
