### ISSUE TITLE
Exception while running `NestedSnippet#on_end`:

### ISSUE THREAD

**Issue by asmerkin** [Shopify/theme-check#524]
❯ theme-check
Checking . ...
Exception while running `NestedSnippet#on_end`:
```
Timeout::Error: execution expired
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/position.rb:19:in `initialize'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/offense.rb:63:in `new'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/offense.rb:63:in `initialize'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/check.rb:95:in `new'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/check.rb:95:in `add_offense'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:42:in `block (2 levels) in on_end'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:17:in `block (2 levels) in with_deep_nested'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:17:in `block (2 levels) in with_deep_nested'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:17:in `block (2 levels) in with_deep_nested'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:13:in `block in with_deep_nested'
  /usr/share/ruby/set.rb:344:in `each_key'
  /usr/share/ruby/set.rb:344:in `each'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:11:in `with_deep_nested'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:17:in `block in with_deep_nested'
  /usr/share/ruby/set.rb:344:in `each_key'
  /usr/share/ruby/set.rb:344:in `each'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:11:in `with_deep_nested'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:17:in `block in with_deep_nested'
  /usr/share/ruby/set.rb:344:in `each_key'
  /usr/share/ruby/set.rb:344:in `each'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:11:in `with_deep_nested'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:17:in `block in with_deep_nested'
  /usr/share/ruby/set.rb:344:in `each_key'
  /usr/share/ruby/set.rb:344:in `each'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:11:in `with_deep_nested'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:41:in `block in on_end'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:40:in `each_pair'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks/nested_snippet.rb:40:in `on_end'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /usr/share/ruby/timeout.rb:112:in `timeout'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks.rb:41:in `call_check_method'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks.rb:11:in `block in call'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks.rb:10:in `each'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/checks.rb:10:in `call'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/analyzer.rb:113:in `finish'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/analyzer.rb:46:in `analyze_theme'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/cli.rb:192:in `check'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/cli.rb:123:in `run!'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/cli.rb:127:in `run'
  /usr/local/share/gems/gems/theme-check-1.5.2/lib/theme_check/cli.rb:149:in `parse_and_run'
  /usr/local/share/gems/gems/theme-check-1.5.2/exe/theme-check:6:in `<top (required)>'
  /usr/local/bin/theme-check:23:in `load'
  /usr/local/bin/theme-check:23:in `<main>'
```

Template: `?`
Node: `?`
Markup:
```

```
Check options: `{:max_nesting_level=>3}
`
Theme Check Version: 1.5.2
Ruby Version: 3.0.2
Platform: x86_64-linux
Muffin mode: activated

**Comment by charlespwd** [comment]
Hi @asmerkin, can you try on the latest version of theme-check? The latest version is 1.9.0.

**Comment by asmerkin** [comment]
@charlespwd  that fixed it. Thank you!
