### ISSUE TITLE
/usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_node.rb:145:in `parseable_markup': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by asmerkin** [Shopify/theme-check#528]
```
theme-check --version
1.9.0
```

```theme-check ./theme
Checking ./theme ...
/usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_node.rb:145:in `parseable_markup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_node.rb:97:in `markup'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:51:in `rescue in call_check_method'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:29:in `call_check_method'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:11:in `block in call'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:10:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:10:in `call'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:32:in `call_checks'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:23:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:14:in `visit_liquid_file'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:54:in `block (2 levels) in analyze_theme'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:51:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:51:in `each_with_index'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:51:in `block in analyze_theme'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check.rb:68:in `with_liquid_c_disabled'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:50:in `analyze_theme'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:192:in `check'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:123:in `run!'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:127:in `run'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:149:in `parse_and_run'
	from /usr/local/bundle/gems/theme-check-1.9.0/exe/theme-check:6:in `<top (required)>'
	from /usr/local/bundle/bin/theme-check:25:in `load'
	from /usr/local/bundle/bin/theme-check:25:in `<main>'
/usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_node.rb:145:in `parseable_markup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_node.rb:97:in `markup'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/offense.rb:43:in `initialize'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/check.rb:95:in `new'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/check.rb:95:in `add_offense'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks/img_lazy_loading.rb:16:in `on_img'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:35:in `catch'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:35:in `catch'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:41:in `call_check_method'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:11:in `block in call'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:10:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/checks.rb:10:in `call'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:32:in `call_checks'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:23:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:24:in `visit'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/html_visitor.rb:14:in `visit_liquid_file'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:54:in `block (2 levels) in analyze_theme'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:51:in `each'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:51:in `each_with_index'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:51:in `block in analyze_theme'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check.rb:68:in `with_liquid_c_disabled'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/analyzer.rb:50:in `analyze_theme'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:192:in `check'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:123:in `run!'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:127:in `run'
	from /usr/local/bundle/gems/theme-check-1.9.0/lib/theme_check/cli.rb:149:in `parse_and_run'
	from /usr/local/bundle/gems/theme-check-1.9.0/exe/theme-check:6:in `<top (required)>'
	from /usr/local/bundle/bin/theme-check:25:in `load'
	from /usr/local/bundle/bin/theme-check:25:in `<main>'
```

**Comment by charlespwd** [comment]
Thanks for the report. Any chance I could get a hold of the theme? You can zip + send to me at cp.clermont@shopify.com.

I could add a null check but I'd like to know what triggered it. There's something we assume somewhere that turns out not to be true.

**Comment by asmerkin** [comment]
@charlespwd maybe you want me to run some other tests?

**Comment by charlespwd** [comment]
There has to be a file in there that cause theme check to trip up. Unfortunately it seems like it's happening outside of our Bug loop, so we don't know which one.

What I'd do if I had the theme on hand (it's kind of a chore, hence why I was suggesting to do it for you):

- Play with the `.theme-check.yml` ignore property and try to bisect which file is causing problem.

  Something like:

  ```
  ignore:
    - assets/
    - config/
    - layout/
    - locales/
    - sections/
    - snippets/
    - templates/
  ```

  And then:

  1. comment half of the ignore fields

  ```
  ignore:
    # - assets/
    # - config/
    # - layout/
    # - locales/
    - sections/
    - snippets/
    - templates/
  ```
  1. run theme-check
  2. Then,
    - Error? The file that makes it trip is in the unignored files
      * Remove the live ignored files
      * Uncomment half of what remains
    - No error? The file that makes it trip is ignored by the filter
      * Remove the commented out files (run theme-check again to make sure there are still no errors)
      * Comment half of what remains
  3. Repeat until you find what is causing the issue.

- Figure out what the problem is with that file.

(BTW I'm a Shopify Employee, not going to steal that theme if that makes a difference. Also under NDA.)

**Comment by charlespwd** [comment]
Unfortunately can't reproduce on my end.

I'm pushing 1.9.2 which will add a bit more info in the error.

We should at least get more info (which file, what line number, etc.) next time it happens. Please do report back the output of the error. If you have this, more partners might also get it.
