### ISSUE TITLE
Exception while running `TranslationKeyExists#on_end`:

### ISSUE THREAD

**Issue by domnappa** [Shopify/theme-check#571]
Getting an error when running theme-check

```
theme-check
Checking . ...
Exception while running `TranslationKeyExists#on_end`:

NoMethodError: undefined method `key?' for "Quantity":String
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:51:in `block in key_exists?'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `each'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `key_exists?'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:35:in `block (2 levels) in on_end'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `each'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `block in on_end'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `each_pair'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `on_end'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:107:in `block in timeout'
  /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:36:in `block in catch'
  /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:36:in `catch'
  /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:36:in `catch'
  /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:123:in `timeout'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks.rb:41:in `call_check_method'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks.rb:11:in `block in call'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `each'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `call'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:153:in `finish'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:63:in `analyze_theme'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/cli.rb:191:in `check'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/cli.rb:123:in `run!'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/cli.rb:127:in `run'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/lib/theme_check/cli.rb:149:in `parse_and_run'
  /usr/local/Cellar/theme-check/1.10.2/gems/theme-check-1.10.2/exe/theme-check:6:in `<top (required)>'
  /usr/local/bin/theme-check:6:in `load'
  /usr/local/bin/theme-check:6:in `<main>'

Theme File: `?`
Node: `?`
Markup:
Line number: ?
Check options: `{}
`
Theme Check Version: 1.10.2
Ruby Version: 3.1.1
Platform: x86_64-darwin20
Muffin mode: activated
```

Only seems to be in one project I have locally, as it runs fine in another projects

**Comment by robertoandrade** [comment]
Getting the same, is there a workaround or any clue as to what causes this in the project?
```
Checking . ...
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ Traceback (most recent call last):
┃       47: from /usr/local/bin/shopify:23:in `<main>'
┃       46: from /usr/local/bin/shopify:23:in `load'
┃       45: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:59:in `<top (required)>'
┃       44: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:49:in `block in <top (required)>'
┃       43: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       42: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       41: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃       40: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃       39: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       38: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃       37: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃       36: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       35: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       34: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       33: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       32: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       31: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       30: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       29: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃       28: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       27: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       26: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       25: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       24: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command.rb:27:in `call'
┃       23: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃       22: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃       21: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:123:in `run!'
┃       20: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:191:in `check'
┃       19: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:63:in `analyze_theme'
┃       18: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:153:in `finish'
┃       17: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `call'
┃       16: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `each'
┃       15: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:11:in `block in call'
┃       14: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:41:in `call_check_method'
┃       13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
┃       12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
┃       11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
┃       10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
┃        9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
┃        8: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:42:in `block in call_check_method'
┃        7: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `on_end'
┃        6: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `each_pair'
┃        5: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `block in on_end'
┃        4: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `each'
┃        3: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:35:in `block (2 levels) in on_end'
┃        2: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `key_exists?'
┃        1: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `each'
┃ /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:51:in `block in key_exists?': undefined method `key?' for "Quantity":String (NoMethodError)
┃       35: from /usr/local/bin/shopify:23:in `<main>'
┃       34: from /usr/local/bin/shopify:23:in `load'
┃       33: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:59:in `<top (required)>'
┃       32: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:49:in `block in <top (required)>'
┃       31: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       30: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       29: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃       28: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃       27: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       26: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃       25: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃       24: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       23: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       22: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       21: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       20: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       19: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       18: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       17: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃       16: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       15: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       14: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       13: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       12: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command.rb:27:in `call'
┃       11: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃       10: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃        9: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:123:in `run!'
┃        8: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:191:in `check'
┃        7: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:63:in `analyze_theme'
┃        6: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:153:in `finish'
┃        5: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `call'
┃        4: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `each'
┃        3: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:11:in `block in call'
┃        2: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:29:in `call_check_method'
┃        1: from /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:54:in `rescue in call_check_method'
┃ /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/bug.rb:20:in `bug': Exception while running `TranslationKeyExists#on_end`: (ThemeCheck::ThemeCheckError)
┃ ```
┃ NoMethodError: undefined method `key?' for "Quantity":String
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:51:in `block in key_exists?'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `each'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `key_exists?'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:35:in `block (2 levels) in on_end'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `each'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `block in on_end'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `each_pair'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `on_end'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:42:in `block in call_check_method'
┃   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
┃   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
┃   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
┃   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
┃   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:41:in `call_check_method'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:11:in `block in call'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `each'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `call'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:153:in `finish'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:63:in `analyze_theme'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:191:in `check'
┃   /Library/Ruby/Gems/2.6.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:123:in `run!'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command.rb:27:in `call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:49:in `block in <top (required)>'
┃   /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.17.0/bin/shopify:59:in `<top (required)>'
┃   /usr/local/bin/shopify:23:in `load'
┃   /usr/local/bin/shopify:23:in `<main>'
┃ ```
┃ 
┃ Theme File: `?`
┃ Node: `?`
┃ Markup:
┃ ```
┃ 
┃ ```
┃ Line number: ?
┃ Check options: `{}
┃ `
┃ Theme Check Version: 1.10.2
┃ Ruby Version: 2.6.8
┃ Platform: universal.x86_64-darwin21
┃ Muffin mode: activated
┃ 
┃ ------------------------
┃ Whoops! It looks like you found a bug in Theme Check.
┃ Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
┃ Or cross your fingers real hard, and try again.
┃ 
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by robertoandrade** [comment]
I was able to drill this down to a few references in the theme that required `products.product.quantity.decrease` as a translation key and the locale files defined `products.product.quantity` as the expected string `Quantity` so it can't navigate further to find `decrease` in it. 

The theme was based of Dawn and apparently they didn't update the locale files to match the latest Dawn's locale resource structure: https://github.com/Shopify/dawn/blob/main/locales/en.default.json#L121

Anyways, the tool itself should throw a better error than crashing like that since it is trying specifically to validate a key exists for that in the locale files.

**Comment by charlespwd** [comment]
Thanks @robertoandrade, that last clue saved me a lot of time.
