### ISSUE TITLE
Crash for missing translation strings

### ISSUE THREAD

**Issue by Mim-Jones** [Shopify/theme-check#600]
┃ Theme check failed with error:
┃ /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/bug.rb:20:in `bug': Exception while running `Offense#correct`: (ThemeCheck::ThemeCheckError)
┃ ```
┃ IndexError: string not matched
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:10:in `[]='
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:10:in `block in set'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each_with_index'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `reduce'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `set'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/corrector.rb:54:in `add_translation'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:63:in `block (2 levels) in add_missing_keys_offense'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:62:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:62:in `block in add_missing_keys_offense'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/offense.rb:149:in `correct'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `correct_offenses'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:192:in `check'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:123:in `run!'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command.rb:27:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:49:in `block in <top (required)>'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:59:in `<top (required)>'
┃   /opt/homebrew/bin/shopify:8:in `load'
┃   /opt/homebrew/bin/shopify:8:in `<main>'
┃ ```
┃ 
┃ Offense:
┃ ```
┃ {
┃   "check": "MatchingTranslations",
┃   "path": "locales/bg-BG.json",
┃   "severity": 1,
┃   "start_row": 0,
┃   "start_column": 0,
┃   "end_row": 0,
┃   "end_column": 0,
┃   "message": "Missing translation keys: general.slider.previous_slide, general.slider.of, general.slider.next_slide"
┃ }
┃ ```
┃ Check options:
┃ ```
┃ {}
┃ 
┃ ```
┃ Markup:
┃ ```
┃ 
┃ ```
┃ Node.Markup:
┃ ```
┃ 
┃ ```
┃ Theme Check Version: 1.10.3
┃ Ruby Version: 3.1.2
┃ Platform: arm64-darwin21
┃ Muffin mode: activated

**Comment by Mim-Jones** [comment]
Theme issue #595 also has the same problem
