### ISSUE TITLE
NoMethodError: undefined method `key?' for "Quantity":String

### ISSUE THREAD

**Issue by vfonic** [Shopify/theme-check#620]
```
Successfully installed ast-2.4.2
Successfully installed parser-3.1.2.0
Successfully installed liquid-5.3.0
Successfully installed theme-check-1.[10](https://github.com/<redacted>/runs/6651782031?check_suite_focus=true#step:4:11).2
4 gems installed
$ theme-check --version
1.10.2
$ theme-check --fail-level style -o json .
Checking . ...
Exception while running `TranslationKeyExists#on_end`:

NoMethodError: undefined method `key?' for "Quantity":String
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:51:in `block in key_exists?'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `each'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:50:in `key_exists?'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:35:in `block (2 levels) in on_end'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `each'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:32:in `block in on_end'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `each_pair'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks/translation_key_exists.rb:31:in `on_end'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:42:in `block in call_check_method'
  /usr/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
  /usr/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
  /usr/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/lib/ruby/3.0.0/timeout.rb:35:in `catch'
  /usr/lib/ruby/3.0.0/timeout.rb:[11](https://github.com/<redacted>/runs/6651782031?check_suite_focus=true#step:4:12)2:in `timeout'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:41:in `call_check_method'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:11:in `block in call'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `each'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/checks.rb:10:in `call'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:153:in `finish'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/analyzer.rb:63:in `analyze_theme'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:191:in `check'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:[12](https://github.com/<redacted>/runs/6651782031?check_suite_focus=true#step:4:13)3:in `run!'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:127:in `run'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:[14](https://github.com/<redacted>/runs/6651782031?check_suite_focus=true#step:4:15)9:in `parse_and_run'
  /usr/lib/ruby/gems/3.0.0/gems/theme-check-1.10.2/exe/theme-check:6:in `<top (required)>'
  /github/home/bin/theme-check:25:in `load'
  /github/home/bin/theme-check:25:in `<main>'


Theme File: `?`
Node: `?`
Markup:

Line number: ?
Check options: `{}
`
Theme Check Version: 1.10.2
Ruby Version: 3.0.3
Platform: x86_64-linux-musl
Muffin mode: activated

------------------------
Whoops! It looks like you found a bug in Theme Check.
Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
Or cross your fingers real hard, and try again.
$ git fetch origin master
From https://github.com/<redacted>
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
$ git diff --name-only --diff-filter=ACMRTUB origin/master
Creating GitHub check...
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /index.js:69:27
    at async /index.js:67:[20](https://github.com/<redacted>/runs/6651782031?check_suite_focus=true#step:4:21)
Error: Unexpected end of JSON input
```

Let me know if there's anything else I need to provide.

**Comment by lukeh-shopify** [comment]
👋🏻 Hi @vfonic! Thanks for reporting this. Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the [CLI](https://github.com/Shopify/cli) or [theme tools](https://github.com/Shopify/theme-tools) repositories. Thanks!
