### ISSUE TITLE
Can't find a parseable tag of name img inside the parseable HTML.

### ISSUE THREAD

**Issue by mohamedhaddi** [Shopify/theme-check#711]
Theme Check stops trying to restart after crashing 5 times with the following trace:

> Checking /Users/haddi/path/to/theme
> rescuing ThemeCheck::ThemeCheckError in handler thread
> Fatal ThemeCheck::ThemeCheckError
> /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/bug.rb:20:in `bug': Can't find a parseable tag of name img inside the parseable HTML. (ThemeCheck::ThemeCheckError)
> 
> Tag name:
>   "img"
> 
> File:
>   snippets/template-banner.liquid
> 
> Line number:
>   10
> 
> Excerpt:
>   ```
>   image: <image object>
> mobile_image: <image object>
> mobile_crop: <string>
> banner_pretext: <string>
> banner_text: <string>
> banner_subheading: <string>
> 
>   ```
> 
> Parseable Excerpt:
>   ```
>   image: <image object>
> mobile_image: <image object>
> mobile_crop: <string>
> banner_pretext: <string>
> banner_text: <string>
> banner_subheading: <string>
> 
>   ```
> Theme Check Version: 1.14.0
> Ruby Version: 3.2.0
> Platform: arm64-darwin22
> Muffin mode: activated
> 
> ------------------------
> Whoops! It looks like you found a bug in Theme Check.
> Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
> Or cross your fingers real hard, and try again.
> 
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_node.rb:154:in `rescue in parseable_markup'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_node.rb:142:in `parseable_markup'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_node.rb:97:in `markup'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/offense.rb:43:in `initialize'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/check.rb:96:in `new'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/check.rb:96:in `add_offense'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks/img_lazy_loading.rb:16:in `on_img'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:36:in `block in catch'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:36:in `catch'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:36:in `catch'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:198:in `timeout'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:41:in `call_check_method'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:11:in `block in call'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:10:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:10:in `call'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:32:in `call_checks'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:23:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:14:in `visit_liquid_file'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:55:in `block (2 levels) in analyze_theme'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:52:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:52:in `each_with_index'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:52:in `block in analyze_theme'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check.rb:68:in `with_liquid_c_disabled'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:51:in `analyze_theme'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/diagnostics_engine.rb:56:in `block in run_full_theme_check'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/diagnostics_engine.rb:55:in `run_full_theme_check'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/diagnostics_engine.rb:28:in `analyze_and_send_offenses'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/handler.rb:278:in `analyze_and_send_offenses'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/handler.rb:108:in `on_text_document_did_open'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:138:in `handle_message'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:109:in `block in handle_messages'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:105:in `loop'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:105:in `handle_messages'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:99:in `block (2 levels) in start_handler_threads'
> /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_node.rb:149:in `parseable_markup': undefined method `[]' for nil:NilClass (NoMethodError)
> 
>         .match(/<\s*#{name}[^>]*>/im, start_index)[0]
>                                                   ^^^
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_node.rb:97:in `markup'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/offense.rb:43:in `initialize'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/check.rb:96:in `new'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/check.rb:96:in `add_offense'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks/img_lazy_loading.rb:16:in `on_img'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:42:in `block in call_check_method'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:36:in `block in catch'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:36:in `catch'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:36:in `catch'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/timeout.rb:198:in `timeout'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:41:in `call_check_method'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:11:in `block in call'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:10:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/checks.rb:10:in `call'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:32:in `call_checks'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:23:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `block in visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:24:in `visit'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/html_visitor.rb:14:in `visit_liquid_file'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:55:in `block (2 levels) in analyze_theme'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:52:in `each'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:52:in `each_with_index'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:52:in `block in analyze_theme'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check.rb:68:in `with_liquid_c_disabled'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/analyzer.rb:51:in `analyze_theme'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/diagnostics_engine.rb:56:in `block in run_full_theme_check'
> 	from /opt/homebrew/Cellar/ruby/3.2.0/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/diagnostics_engine.rb:55:in `run_full_theme_check'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/diagnostics_engine.rb:28:in `analyze_and_send_offenses'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/handler.rb:278:in `analyze_and_send_offenses'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/handler.rb:108:in `on_text_document_did_open'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:138:in `handle_message'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:109:in `block in handle_messages'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:105:in `loop'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:105:in `handle_messages'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/language_server/server.rb:99:in `block (2 levels) in start_handler_threads'
> Closing server... status code = 2
> rescuing ThemeCheck::LanguageServer::DoneStreaming in jsonrpc thread
> /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:34:in `write': closed stream (IOError)
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:34:in `write'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:226:in `block in activate'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/context.rb:55:in `puts'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/context.rb:55:in `puts'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/context.rb:55:in `puts'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/context.rb:415:in `puts'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/exception_reporter.rb:11:in `report'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:31:in `handle_exception'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:71:in `block in install!'
> /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/friendly_errors.rb:124:in `exit': exit (SystemExit)
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/friendly_errors.rb:124:in `rescue in with_friendly_errors'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/friendly_errors.rb:115:in `with_friendly_errors'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/exe/bundle:33:in `<top (required)>'
> 	from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
> 	from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'
> /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:47:in `exit': exit (SystemExit)
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:47:in `<top (required)>'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify:25:in `load'
> 	from /Users/haddi/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify:25:in `<top (required)>'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/cli/exec.rb:58:in `load'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/cli/exec.rb:23:in `run'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/cli.rb:491:in `exec'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/cli.rb:34:in `dispatch'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/cli.rb:28:in `start'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/exe/bundle:45:in `block in <top (required)>'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
> 	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/exe/bundle:33:in `<top (required)>'
> 	from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
> 	from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'
> [Info  - 11:51:39 PM] Connection to server got closed. Server will restart.
> 

The excerpt mentioned in the debug info is a Liquid comment, here is the whole excerpt:

```Liquid
{% comment %}
Values
wide_display: <boolean>
background_style: <string>
image: <image object>
mobile_image: <image object>
mobile_crop: <string>
banner_pretext: <string>
banner_text: <string>
banner_subheading: <string>
banner_button1: <string>
banner_button1_link: <link>
banner_button1_style: <string>
banner_button2: <string>
banner_button2_link: <link>
banner_button2_style: <string>
show_caption: <boolean>
{% endcomment %}
```

I'm using the official VS Code extension (Shopify Liquid).

**Comment by BaoJay** [comment]
I have the same issue when run `shopify theme check` 

![image](https://github.com/Shopify/theme-check/assets/102657300/22c4ab0a-024b-4a11-b326-979641c1f1cf)

I'm using [Turbo Theme](https://outofthesandbox.com/collections/turbo-theme), Shopify CLI version: 3.51.1
I'm looking forward to fixing it soon.

**Comment by charlespwd** [comment]
Try `shopify theme check --dev-preview`. Our next version of theme-check over at [Shopify/theme-tools](/Shopify/theme-tools) shouldn't have this problem.

**Comment by lukeh-shopify** [comment]
👋🏻 Hi @mohamedhaddi! Thanks for reporting this. Unfortunately the Ruby version of theme check has been deprecated for some time. Would you be able to confirm you are still having issues when using our [maintained version of theme check](https://shopify.dev/docs/storefronts/themes/tools/theme-check)? This is done using either the latest version of the Shopify CLI, or via the Shopify Liquid Visual Studio Code extension.

If you are still having issues, please raise an issue over in the [CLI](https://github.com/Shopify/cli) or [theme tools](https://github.com/Shopify/theme-tools) repositories. Thanks!
