### ISSUE TITLE
SocketSocker::HostNotPermittedError: Failed to open TCP connection to raw.githubusercontent.com:443 (The host raw.githubusercontent.com is not permitted)

### ISSUE THREAD

**Issue by KenjiDuggan** [Shopify/theme-check#733]
**Describe the bug**

```
┃ Delivery enabled on shop 1
┣━━ sh[52704] May 26 14:17:10
┃ + APP_ID=6339591
┃ + UUID=83d8bfd8-d404-4f9a-ae93-22363b03f58b
┃ + DIR_PATH=/tmp/delivery-promise
┃ + TITLE=delivery-promise-app-extension
┃ + bin/rake online_store:theme_app_extensions:create
┣━━ sh[54530] May 26 14:17:20
┃ Exception while running `UndefinedObject#on_end`:
┃ ```
┃ SocketSocker::HostNotPermittedError: Failed to open TCP connection to raw.githubusercontent.com:443 (The host raw.githubusercontent.com is not permitted)
┃   /home/spin/.bundle/shopify/gems/socket-socker-3.0.4/lib/socket_socker/request.rb:25:in `ensure_permitted!'
┃   /home/spin/.bundle/shopify/gems/socket-socker-3.0.4/lib/socket_socker/patches/tcp_socket_patch.rb:7:in `initialize'
┃   /home/spin/src/github.com/Shopify/shopify/components/platform/essentials/lib/http_host_restriction.rb:83:in `open'
┃   /home/spin/src/github.com/Shopify/shopify/components/platform/essentials/lib/http_host_restriction.rb:83:in `open'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1271:in `block in connect'
┃   /home/spin/.bundle/shopify/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
┃   /home/spin/.bundle/shopify/gems/timeout-0.3.2/lib/timeout.rb:196:in `timeout'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1269:in `connect'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/net_http.rb:97:in `block (2 levels) in connect'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/adapter.rb:84:in `mark_resource_as_acquired'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/adapter.rb:44:in `block in acquire_semian_resource'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/protected_resource.rb:36:in `block (2 levels) in acquire'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/protected_resource.rb:62:in `acquire_bulkhead'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/protected_resource.rb:34:in `block in acquire'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/protected_resource.rb:52:in `block in acquire_circuit_breaker'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/circuit_breaker.rb:174:in `maybe_with_half_open_resource_timeout'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/circuit_breaker.rb:45:in `acquire'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/protected_resource.rb:51:in `acquire_circuit_breaker'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/protected_resource.rb:33:in `acquire'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/adapter.rb:43:in `acquire_semian_resource'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/net_http.rb:97:in `block in connect'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/net_http.rb:139:in `with_cleared_dynamic_options'
┃   /home/spin/.bundle/shopify/gems/semian-0.19.1/lib/semian/net_http.rb:94:in `connect'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-instrumentation-net_http-0.20.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:59:in `block in connect'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace.rb:72:in `block in with_span'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/context.rb:87:in `with_value'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace.rb:72:in `with_span'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace/tracer.rb:29:in `in_span'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-instrumentation-net_http-0.20.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:58:in `connect'
┃   /home/spin/src/github.com/Shopify/shopify/lib/instrumentation/web_external.rb:16:in `block in connect'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activesupport/lib/active_support/notifications.rb:206:in `instrument'
┃   /home/spin/src/github.com/Shopify/shopify/lib/instrumentation/web_external.rb:15:in `connect'
┃   /home/spin/src/github.com/Shopify/shopify/lib/patches/net_http/ssl_errors.rb:11:in `connect'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1237:in `start'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:687:in `start'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_manager.rb:101:in `open_uri'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_manager.rb:77:in `block in download_file'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_manager.rb:76:in `open'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_manager.rb:76:in `download_file'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_manager.rb:25:in `block in download'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_manager.rb:24:in `each'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_manager.rb:24:in `download'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_index.rb:62:in `local_path!'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_index.rb:58:in `load_file'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/source_index.rb:22:in `objects'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/shopify_liquid/object.rb:15:in `labels'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/checks/undefined_object.rb:109:in `on_end'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/checks.rb:42:in `block in call_check_method'
┃   /home/spin/.bundle/shopify/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
┃   /home/spin/.bundle/shopify/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
┃   /home/spin/.bundle/shopify/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
┃   /home/spin/.bundle/shopify/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
┃   /home/spin/.bundle/shopify/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/checks.rb:41:in `call_check_method'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/checks.rb:11:in `block in call'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/checks.rb:10:in `each'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/checks.rb:10:in `call'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/analyzer.rb:170:in `finish'
┃   /home/spin/.bundle/shopify/bundler/gems/theme-check-ca4d6d1e2f81/lib/theme_check/analyzer.rb:64:in `analyze_theme'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_check_runner.rb:29:in `block in run_theme_check_for'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_check_runner.rb:43:in `with_default_core_liquid_tags'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_check_runner.rb:22:in `run_theme_check_for'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_check_runner.rb:16:in `perform'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_extension/plugins/pre_update_draft.rb:162:in `validate_with_theme_check'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_extension/plugins/pre_update_draft.rb:57:in `block in perform'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace.rb:72:in `block in with_span'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/context.rb:87:in `with_value'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace.rb:72:in `with_span'
┃   /home/spin/.bundle/shopify/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace/tracer.rb:29:in `in_span'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_extension/plugins/pre_update_draft.rb:56:in `perform'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
┃   /home/spin/src/github.com/Shopify/shopify/components/online_store/app/models/online_store/app_extension/theme_extension/plugins/theme_extension_specification.rb:29:in `pre_update_version'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/point_registry.rb:26:in `block in <class:PointRegistry>'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategies/with_original.rb:14:in `execute_plugin'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy.rb:32:in `safely_execute_single'
┃   /home/spin/.bundle/shopify/gems/shopify-adt-1.1.0/lib/shopify/adt/result.rb:418:in `map'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy.rb:27:in `execute_single'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy.rb:20:in `block (2 levels) in execute'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/metrics.rb:12:in `measure_metrics'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy.rb:19:in `block in execute'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy.rb:18:in `each'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy.rb:18:in `inject'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy.rb:18:in `execute'
┃   /home/spin/.bundle/shopify/gems/shopify-adt-1.1.0/lib/shopify/adt/result.rb:358:in `and_then'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy_builder.rb:23:in `with_original'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/plugins/execution/strategy_builder.rb:14:in `block in build_for'
┃   /home/spin/.bundle/shopify/gems/shopify-adt-1.1.0/lib/shopify/adt/result.rb:358:in `and_then'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/public/apps/extensions/management/update.rb:70:in `perform_update'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/public/apps/extensions/versions/version.rb:75:in `block in while_locked'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/repositories/mutation_repository.rb:35:in `block (2 levels) in while_locked'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activerecord/lib/active_record/locking/pessimistic.rb:97:in `block in with_lock'
┃   /home/spin/src/github.com/Shopify/shopify/components/platform/podding/lib/podding/patches/active_record.rb:50:in `block (2 levels) in transaction'
┃   /home/spin/src/github.com/Shopify/shopify/components/platform/podding/app/utils/podding/verifier/cross_db_transaction.rb:42:in `with_transaction'
┃   /home/spin/src/github.com/Shopify/shopify/components/platform/podding/lib/podding/patches/active_record.rb:49:in `block in transaction'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:491:in `block in within_new_transaction'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:488:in `within_new_transaction'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:335:in `transaction'
┃   /home/spin/src/github.com/Shopify/shopify/components/platform/podding/lib/podding/patches/active_record.rb:48:in `transaction'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activerecord/lib/active_record/transactions.rb:212:in `transaction'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activerecord/lib/active_record/transactions.rb:301:in `transaction'
┃   /home/spin/.bundle/shopify/bundler/gems/rails-ef04fbb3b256/activerecord/lib/active_record/locking/pessimistic.rb:95:in `with_lock'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/repositories/mutation_repository.rb:34:in `block in while_locked'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/repositories/repository_result_handling.rb:17:in `block (2 levels) in as_result'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/validation/active_record_handling.rb:12:in `active_record_errors_as_result'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/repositories/repository_result_handling.rb:16:in `block in as_result'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/public/apps/extensions/errors/internal/exception_handling.rb:26:in `smart_properties_errors_as_result_from_result'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/repositories/repository_result_handling.rb:15:in `as_result'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/models/extensions/repositories/mutation_repository.rb:32:in `while_locked'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/public/apps/extensions/versions/version.rb:75:in `while_locked'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/public/apps/extensions/management/update.rb:62:in `block in perform'
┃   /home/spin/.bundle/shopify/gems/shopify-adt-1.1.0/lib/shopify/adt/result.rb:358:in `and_then'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `bind_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:256:in `validate_call'
┃   /home/spin/.bundle/shopify/gems/sorbet-runtime-0.5.10805/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/public/apps/extensions/management/update.rb:61:in `perform'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/business_process.rb:27:in `block in perform'
┃   /home/spin/src/github.com/Shopify/shopify/components/platform/app/utils/time_instrumenter.rb:11:in `track_time'
┃   /home/spin/src/github.com/Shopify/shopify/components/apps/app/services/apps/business_process.rb:25:in `perform'
┃   /home/spin/src/github.com/Shopify/shopify/lib/tasks/online_store_theme_extension.rake:215:in `update_promote_publish_draft_version_for'
┃   /home/spin/src/github.com/Shopify/shopify/lib/tasks/online_store_theme_extension.rake:105:in `block (3 levels) in <module:OnlineStoreThemeExtension>'
┃   /home/spin/src/github.com/Shopify/shopify/lib/rake_task_with_pod_selection.rb:17:in `block in unpodded_task'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
┃   /home/spin/.bundle/shopify/gems/bugsnag-5.5.0.1/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
┃   /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
┃   /home/spin/src/github.com/Shopify/shopify/bin/rake:10:in `<main>'
┃   <internal:/opt/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
┃   <internal:/opt/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
┃   -e:1:in `<main>'
┃ ```
┃ Theme File: `?`
┃ Node: `?`
┃ Markup:
┃ ```
┃ ```
┃ Line number: ?
┃ Check options: `{:exclude_snippets=>true, :config_type=>:theme_app_extension}
┃ `
┃ Theme Check Version: 1.15.0
┃ Ruby Version: 3.2.2
┃ Platform: x86_64-linux
┃ Muffin mode: activated
┃ ------------------------
┃ Whoops! It looks like you found a bug in Theme Check.
┃ Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
┃ Or cross your fingers real hard, and try again.
┃ Running via Spring preloader in process 54530
┃ running spring after_fork
┣━━ sh[39668] May 26 14:17:20
┃ spin-init script failed: /home/spin/src/github.com/Shopify/shopify/.spin/bin/init/install-apps
┣━━ systemd[1] May 26 14:17:20
┃ spin-init-1@shopify--shopify.service: Main process exited, code=exited, status=1/FAILURE
┃ spin-init-1@shopify--shopify.service: Failed with result 'exit-code'.
┃ Failed to start [Spin] Initializer seeds {shopify--shopify}.
```
**Expected**

**Actual**

**Stack trace**
```
<!-- When provided, please include the entire error message in here -->
```

**Debugging information**
- OS [e.g. Windows, Mac, Linux]
- Version (output of `theme-check --version` in a terminal)

**Additional context**

**Comment by klizas** [comment]
+1

**Comment by charlespwd** [comment]
Ugh. Right. Shopify core doesn't want to load raw.github.com data which is very fair. We use that to update the docs internally. We might need to find a way to turn that off from Shopify core.
