### ISSUE TITLE
Mention that it only works on Ruby 2.7+

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/theme-check#98]
My default Ruby version is `2.6.3` and when this is installed it throws a SyntaxError:

```bash
[retracted] on  develop [$] is 📦 v1.0.0-alpha.1 via ⬢ v13.14.0 took 4s
➜ gem install theme-check
Fetching theme-check-0.1.2.gem
Fetching liquid-5.0.0.gem
Fetching nokogumbo-2.0.4.gem
Successfully installed liquid-5.0.0
Building native extensions. This could take a while...
Successfully installed nokogumbo-2.0.4
Successfully installed theme-check-0.1.2
Parsing documentation for liquid-5.0.0
Installing ri documentation for liquid-5.0.0
Parsing documentation for nokogumbo-2.0.4
unable to convert "\xE3" from ASCII-8BIT to UTF-8 for ext/nokogumbo/tmp/x86_64-apple-darwin18.5.0/ports/libxml2/2.9.10/libxml2-2.9.10/os400/libxmlrpg/c14n.rpgle, skipping
unable to convert "\xA9" from ASCII-8BIT to UTF-8 for ext/nokogumbo/tmp/x86_64-apple-darwin18.5.0/ports/libxml2/2.9.10/libxml2-2.9.10/result/HTML/doc3.htm, skipping
unable to convert "\xA9" from ASCII-8BIT to UTF-8 for ext/nokogumbo/tmp/x86_64-apple-darwin18.5.0/ports/libxml2/2.9.10/libxml2-2.9.10/test/HTML/doc3.htm, skipping
unable to convert "\xFC" from ASCII-8BIT to UTF-8 for ext/nokogumbo/tmp/x86_64-apple-darwin18.5.0/ports/libxml2/2.9.10/libxml2-2.9.10/test/HTML/wired.html, skipping
unable to convert "\xC0" from ASCII-8BIT to UTF-8 for ext/nokogumbo/tmp/x86_64-apple-darwin18.5.0/ports/libxml2/2.9.10/libxml2-2.9.10/test/XInclude/ents/isolatin.txt, skipping
Installing ri documentation for nokogumbo-2.0.4
Parsing documentation for theme-check-0.1.2
Installing ri documentation for theme-check-0.1.2
Done installing documentation for liquid, nokogumbo, theme-check after 96 seconds
3 gems installed

[retracted] on  develop [$] is 📦 v1.0.0-alpha.1 via ⬢ v13.14.0 took 2m 2s
➜ theme-check src
Traceback (most recent call last):
	10: from /Users/dangamble/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	 9: from /Users/dangamble/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	 8: from /Users/dangamble/.rvm/gems/ruby-2.6.3/bin/theme-check:23:in `<main>'
	 7: from /Users/dangamble/.rvm/gems/ruby-2.6.3/bin/theme-check:23:in `load'
	 6: from /Users/dangamble/.rvm/gems/ruby-2.6.3/gems/theme-check-0.1.2/exe/theme-check:4:in `<top (required)>'
	 5: from /Users/dangamble/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /Users/dangamble/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/dangamble/.rvm/gems/ruby-2.6.3/gems/theme-check-0.1.2/lib/theme_check.rb:8:in `<top (required)>'
	 2: from /Users/dangamble/.rvm/gems/ruby-2.6.3/gems/theme-check-0.1.2/lib/theme_check.rb:8:in `require_relative'
	 1: from /Users/dangamble/.rvm/gems/ruby-2.6.3/gems/theme-check-0.1.2/lib/theme_check/liquid_check.rb:2:in `<top (required)>'
/Users/dangamble/.rvm/gems/ruby-2.6.3/gems/theme-check-0.1.2/lib/theme_check/liquid_check.rb:2:in `require_relative': /Users/dangamble/.rvm/gems/ruby-2.6.3/gems/theme-check-0.1.2/lib/theme_check/parsing_helpers.rb:9: syntax error, unexpected .., expecting ']' (SyntaxError)
...       yield scanner.matched[..-2]
...
```

Worked perfectly fine on 2.7.x though 👍

**Comment by macournoyer** [comment]
Thanks for reporting! Fixed in #99
